project:

  type: website

website:

  title: "MAT, PhD"

  favicon: images/matt-turner-headshot-cafecito.png

  navbar:
    right:
      - text: "<i title='Email' class='fa-solid fa-envelope'></i>"
        href: "mailto:matt@mat.phd"
      - text: "<i title='LinkedIn' class='fa-brands fa-linkedin'></i>"
        href: "https://www.linkedin.com/in/mt-digital/"
      - text: "<i title='GitHub' class='fa-brands fa-github'></i>"
        href: "https://github.com/mt-digital"
      - text: "<i title='Instagram' class='fa-brands fa-instagram'></i>"
        href: "https://instagram.com/matthewadamturnerphd"
      - text: CV
        href: turner_cv.pdf

    pinned: true
    collapse: false

format:
  html:
    theme: styles.scss
    toc: false

